# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
    ports:
      - 3306:3306

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - 1433:1433

