# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
    ports:
      - 3306:3306

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - 1433:1433

  postgresql:
    image: postgres:13.0
    environment:
      POSTGRES_PASSWORD: "P@ssw0rd"
    ports:
      - 5432:5432

  mongodb:
    image: mongo:4.0.20
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "P@ssw0rd"
    ports:
      - 27017:27017

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      discovery.type: "single-node"
    ports:
        - 9200:9200
        - 9300:9300

